### ISSUE TITLE
[Bug]: Strict Mode in In-app messages

### ISSUE THREAD

**Issue by auxDK** [braze-inc/braze-android-sdk#19]
### Braze Android SDK Version

29.0.1

### Steps To Reproduce

Incoming html in-app messages on a device

### Expected Behavior

Not have an alert about strict mode

### Actual Incorrect Behavior

We have an alert

`Process:X, PID: 2426
                                                      android.os.strictmode.DiskReadViolation
                                                      	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
                                                      	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                      	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                      	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7795)
                                                      	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                                                      	at java.io.File.exists(File.java:813)
                                                      	at android.app.ContextImpl.getDataDir(ContextImpl.java:2962)
                                                      	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:704)
                                                      	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:931)
                                                      	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:553)
                                                      	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
                                                      	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:217)
                                                      	at com.braze.configuration.RuntimeAppConfigurationProvider.<init>(SourceFile:2)
                                                      	at com.braze.configuration.CachedConfigurationProvider.<init>(SourceFile:16)
                                                      	at com.braze.configuration.BrazeConfigurationProvider.<init>(SourceFile:1)
                                                      	at com.braze.ui.inappmessage.views.InAppMessageHtmlBaseView.getMessageWebView(InAppMessageHtmlBaseView.kt:108)
                                                      	at com.braze.ui.inappmessage.views.InAppMessageHtmlBaseView.setWebViewContent(InAppMessageHtmlBaseView.kt:215)
                                                      	at com.braze.ui.inappmessage.views.InAppMessageHtmlBaseView.setWebViewContent$default(InAppMessageHtmlBaseView.kt:210)
                                                      	at com.braze.ui.inappmessage.factories.DefaultInAppMessageHtmlViewFactory.createInAppMessageView(DefaultInAppMessageHtmlViewFactory.kt:43)
                                                      	at com.braze.ui.inappmessage.factories.DefaultInAppMessageHtmlViewFactory.createInAppMessageView(DefaultInAppMessageHtmlViewFactory.kt:22)
                                                      	at com.braze.ui.inappmessage.BrazeInAppMessageManager.displayInAppMessage(BrazeInAppMessageManager.kt:520)
                                                      	at com.braze.ui.inappmessage.utils.BackgroundInAppMessagePreparer$displayPreparedInAppMessage$2.invokeSuspend(BackgroundInAppMessagePreparer.kt:274)
                                                      	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                      	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                      	at android.os.Handler.handleCallback(Handler.java:942)
                                                      	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                      	at android.os.Looper.loopOnce(Looper.java:201)
                                                      	at android.os.Looper.loop(Looper.java:288)
                                                      	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                      	at java.lang.reflect.Method.invoke(Native Method)
                                                      	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)`

**Comment by auxDK** [comment]
Hi there, any news?

**Comment by radixdev** [comment]
Sorry for the lack of an update,

This should be fixed in 30.0.0 of the SDK. Thank you for the detailed report!

**Comment by SolaBe** [comment]
Hi, still reproduce on version 32.0.0
