### ISSUE TITLE
[Bug]: Strict Mode DiskReadViolation

### ISSUE THREAD

**Issue by auxDK** [braze-inc/braze-android-sdk#22]
### Braze Android SDK Version

29.0.1

### Steps To Reproduce

Call the method `Braze.disableSdk(context)`

### Expected Behavior

Not have an alert about strict mode

### Actual Incorrect Behavior

We have an alert

```
Fatal Exception: android.os.strictmode.DiskReadViolation:
       at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1658)
       at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
       at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
       at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8610)
       at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
       at java.io.File.exists(File.java:813)
       at android.app.SharedPreferencesImpl$EditorImpl.isSpeg(SharedPreferencesImpl.java:505)
       at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:517)
       at bo.app.g5.a(SourceFile:5)
       at com.braze.Braze$Companion.disableSdk(SourceFile:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Additional Information

Device
Brand:Samsung
Model:Galaxy S20 FE

Operating System
Version:Android 13

**Comment by radixdev** [comment]
Hi @auxDK ,
`disableSdk()` by design is made to occur in a blocking manner so that user data collection can cease as quickly as possible. You can alternatively call `disableSdk()` in a thread or coroutine so that the shared pref call doesn't occur on your main thread.

**Comment by auxDK** [comment]
@radixdev Okay, I can do that, but could you annotate or write some notes in the document about this? I'm not sure when and where I should call methods in IO, as it's not intuitive.

**Comment by radixdev** [comment]
Hi @auxDK ,

Will do!
