### ISSUE TITLE
[Bug]: InAppMessageWebView ANR

### ISSUE THREAD

**Issue by arcmaksim** [braze-inc/braze-android-sdk#27]
### Braze Android SDK Version

30.2.0

### Steps To Reproduce

Unfortunately, we don't have a way to reproduce this issue, only logs we receive from DataDog RUM.

### Expected Behavior

No such logs

### Actual Incorrect Behavior

The stacktrace 
```
at com.android.webview.chromium.WebViewChromium.init(chromium-TrichromeWebViewGoogle.aab-stable-626111931:97)
...
at android.webkit.WebView.<init>(WebView.java:338)
at com.braze.ui.inappmessage.views.InAppMessageWebView.<init>(InAppMessageWebView.java:13)
...
at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
at com.braze.ui.inappmessage.factories.DefaultInAppMessageHtmlViewFactory.createInAppMessageView(DefaultInAppMessageHtmlViewFactory.java:31)
at com.braze.ui.inappmessage.factories.DefaultInAppMessageHtmlViewFactory.createInAppMessageView(DefaultInAppMessageHtmlViewFactory.java:22)
at com.braze.ui.inappmessage.BrazeInAppMessageManager.displayInAppMessage(BrazeInAppMessageManager.java:520)
at com.braze.ui.inappmessage.utils.BackgroundInAppMessagePreparer$displayPreparedInAppMessage$2.invokeSuspend(BackgroundInAppMessagePreparer.java:274)
```

### Additional Information

This ANR is being reported by [DataDog RUM](https://www.datadoghq.com/product/real-user-monitoring/). But we don't see this issue on Crashlytics or Play Console.

We are not sure if you can mitigate it on your side, or if ANR just propagates from WebView through Braze.

**Comment by jocelynzz** [comment]
Hi @arcmaksim,

To help us further investigate the issue, it would be great if you could provide the number of users and devices affected by this ANR. Did this issue start only after you upgraded the SDK to 30.2.0?

Additionally, can you contact [support@braze.com](mailto:support@braze.com) with campaign details and ANR reports (if available)?

Thanks!'
