### ISSUE TITLE
[Bug]: Crash when removing view from parent IndexOutOfBoundsException

### ISSUE THREAD

**Issue by carlos-prezzee** [braze-inc/braze-android-sdk#29]
### Braze Android SDK Version

30.1.0

### Steps To Reproduce

This Braze crash is the number 1 top crash from our app in production. We have not identified a way to reproduce the crash.

### Expected Behavior

App should not crash when activity goes in pause

### Actual Incorrect Behavior

App crash when activity goes in pause (not easy to reproduce)

### Verbose Logs

```shell
Caused by java.lang.IndexOutOfBoundsException:
       at android.view.ViewGroup.removeFromArray(ViewGroup.java:6215)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6403)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6365)
       at android.view.ViewGroup.removeView(ViewGroup.java:6296)
       at com.braze.ui.support.ViewUtils.removeViewFromParent(ViewUtils.kt:28)
       at com.braze.ui.inappmessage.BrazeInAppMessageManager.unregisterInAppMessageManager(BrazeInAppMessageManager.kt:259)
       at com.braze.BrazeActivityLifecycleCallbackListener.onActivityPaused(BrazeActivityLifecycleCallbackListener.kt:122)
       at android.app.Application.dispatchActivityPaused(Application.java:485)
       at android.app.Activity.dispatchActivityPaused(Activity.java:1454)
       at android.app.Activity.onPause(Activity.java:2392)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:282)
       at android.app.Activity.performPause(Activity.java:8400)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5261)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5222)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6040)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5958)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Additional Information

We are using the recommended [Activity lifecycle callback integration](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration#step-4-tracking-user-sessions-in-android)

**Comment by radixdev** [comment]
Hello @carlos-prezzee ,

We've identified the issue and will have a fix ready for the next release. Thank you for filing.

Julian

**Comment by carlos-prezzee** [comment]
Thanks @radixdev - looking forward to updating the new release

**Comment by radixdev** [comment]
Hello @carlos-prezzee ,

This was released in 31.0.0 just now. Thank you for your patience here.

**Comment by carlos-prezzee** [comment]
Thanks @radixdev for the heads up - will try the latest version 🙌

**Comment by carlos-prezzee** [comment]
@radixdev We haven't found this crash in the latest version of our app in production. Will keep you posted if anything appears but so far everything indicates that this is resolved.
