### ISSUE TITLE
[Bug]: jdk.internal.misc.Unsafe.park

### ISSUE THREAD

**Issue by janaksuthar-enc** [braze-inc/braze-android-sdk#31]
### Braze Android SDK Version

30.3.0

### Steps To Reproduce

As per the log, this method is getting ANR

setPushNotificationSubscriptionType

### Expected Behavior

Should not create ANR

### Actual Incorrect Behavior

ANR is getting for many users

### Verbose Logs

```shell
main (timed waiting):tid=1 systid=30487 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:91)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:85)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:9)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:15)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:9)
       at t55649196.m5c55e4a0.k797572f3.t8e970ce4(unavailable:36)
       at t55649196.m5c55e4a0.k797572f3.getCurrentUser(SourceFile:1)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.zd76f9813.d021e715b.m5c55e4a0.ee1fd6ba8.setPushNotificationSubscriptionType(unavailable:22)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.y77eb7b70.x22c24678.p9d5e45b0(unavailable:60)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.y77eb7b70.x22c24678.b25920628(unavailable:9)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.y77eb7b70.x22c24678$ca044e827$1.invoke(SourceFile:5)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.y77eb7b70.x22c24678$ca044e827$1.invoke(SourceFile:1)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.qe9d7ecf2.r6efb82ac.se4e1f682.requestPermissions(unavailable:99)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.qe9d7ecf2.r6efb82ac.p5c0587ce$h7b0fed00.zfe4715f0(unavailable:16)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.y77eb7b70.x22c24678.requestPermissions(unavailable:38)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989.o1eeac866(unavailable:44)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989.h4486e06b(unavailable:12)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989.wccd3ab75(unavailable:9)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989$w8d912e17$1$1$1.h57fc69a7(unavailable:9)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989$w8d912e17$1$1$1.r106c1bda(unavailable:9)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989$w8d912e17$1$1$1$1.emit(SourceFile:2)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.m1cb83989$w8d912e17$1$1$1$1.emit(SourceFile:1)
       at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:400)
       at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(StateFlow.kt:21)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
       at kotlinx.coroutines.CoroutineContextKt.withContinuationContext(CoroutineContext.kt:119)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
       at kotlinx.coroutines.DispatchedTaskKt.runUnconfinedEventLoop(DispatchedTask.kt:214)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:56)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:16)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:517)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:19)
       at kotlinx.coroutines.flow.StateFlowSlot.makePending(StateFlow.kt:66)
       at kotlinx.coroutines.flow.StateFlowImpl.updateState(StateFlow.kt:353)
       at kotlinx.coroutines.flow.StateFlowImpl.setValue(StateFlow.kt:14)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.pd9de8f35.cce07e5a6(unavailable:97)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.pd9de8f35.gb38dae6f(unavailable:9)
       at t55649196.ief4fea39.s80dc7ca3.s66f4d0f1.ui.ec636fe97.yc420334c.pd9de8f35$cce07e5a6$1.invokeSuspend(unavailable:20)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
       at kotlinx.coroutines.CoroutineContextKt.withContinuationContext(CoroutineContext.kt:118)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:90)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8893)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by bryanlogan** [comment]
Does this recreate reliably?  If so, is there a certain campaign that's causing it?

Also, it looks like you might be obfuscating the code yourself, so it's a little bit harder for us to see the code path. Is any of this code in wrappers that you've made? If so, what does that code look like?

If you don't want to post anything in Github, feel free to send it to Braze support and just reference this issue.

**Comment by indiascope** [comment]
In **Braze SDK 30.3.0**, many of our users are experiencing an issue. From **Firebase** and **Google Play Stacktrace**, we observe this issue in **Android 13** and **14**, with most occurrences on **Android 14** and **Samsung** devices.

Upon analyzing the stacktraces, we’ve identified a common pattern: **Braze** method calls preceding ANRs. Specifically, the following methods are invoked just before ANRs occur: 
`setPushNotificationSubscriptionType`, `setCustomAttributeArray`, and `addToCustomAttributeArray`. 

Additionally, we observe references to `runBlocking` and `joinBlocking` in the stack traces. It’s likely that calling `runBlocking` on the main thread is causing the Android app to become deadlocked indefinitely.

Here's a related article discussing this issue: [How to Deadlock Your Android App with runBlocking](https://proandroiddev.com/how-to-deadlock-your-android-app-with-runblocking-8dab02c2624d)

**Comment by radixdev** [comment]
> Also, what do you think about using the synchronous method with CoroutineDispatcher IO? Will this address the ANR problem?

Calling the synchronous method via coroutine should alleviate the ANR as long as its not on the main dispatcher, so that code looks good to me. 

> Does the synchronous method cause ANR issues?

It could contribute to an ANR if called on the main thread, yes.
