### ISSUE TITLE
[Bug]: Crash at line 311 of AppboyIntegration on BrazeProperties instatiation

### ISSUE THREAD

**Issue by isolino** [braze-inc/braze-android-sdk#42]
### Braze Android SDK Version

15.0.1

### Steps To Reproduce

Add a list of Objects as a parameter of segment Properties.
```
    fun getProperties() : Properties {
        return Properties().apply { 
            put("myParameter", listOf<Any>(someObject, otherObject))
        }
    }
```
When the integration try com convert the properties to JSON object. The myParameter prop should be a JSONArray with NULLs insised.

### Expected Behavior

Send the correct TrackPayload to Braze

### Actual Incorrect Behavior

Crash on BrazeProperties instantiation

### Verbose Logs

```shell
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 
                                                                                                    Caused by: org.json.JSONException: Value at 0 is null.
                                                                                                    	at org.json.JSONArray.get(JSONArray.java:291)
at bo.app.r.a(SourceFile:1237)
at com.braze.models.outgoing.BrazeProperties.clean(SourceFile:16)
at com.braze.models.outgoing.BrazeProperties.clean$default(SourceFile:1)
at com.braze.models.outgoing.BrazeProperties.<init>(SourceFile:39)
at com.segment.analytics.android.integrations.appboy.AppboyIntegration.track(AppboyIntegration.java:311)
at com.segment.analytics.IntegrationOperation.track(IntegrationOperation.java:291)
at com.segment.analytics.IntegrationOperation$8$1.invoke(IntegrationOperation.java:216)
at com.segment.analytics.MiddlewareChainRunner.proceed(MiddlewareChainRunner.java:64)
at com.segment.analytics.IntegrationOperation.runMiddlewareChain(IntegrationOperation.java:184)
at com.segment.analytics.IntegrationOperation$8.run(IntegrationOperation.java:199)
at com.segment.analytics.Analytics.performRun(Analytics.java:1654)
at com.segment.analytics.Analytics$10.run(Analytics.java:802)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

### Additional Information

I'm facing a problem with appboy-segment-integration 15.0.1 with android-braze-sdk 26.3.2.

I recently migrate from appboy-segment-integration 10.0.0 to 15.0.1.

Sometimes some properties of the trackPayload at the AppboyIntegration.track() is converted into a JSONArray of NULLS.
This JSONArrays geneate a crash when passed to BrazeProperties constructor

Inside verbose log.
The problematic parameter appears as [null, null]

**Comment by bryanlogan** [comment]
Segment has moved away from their segment-android library and instead to their `segment-kotlin` library. The Braze integration for that is at: https://github.com/braze-inc/braze-segment-kotlin

Are you able to use that?

One thing that is a little odd is that segment uses `kotlinx.serialization.json.JsonObject` while Braze uses `org.json.JSONObject`.  So are you passing an org.json.JSONArray and or.json.JSONObjects?

Are you putting nulls in some arrays? If you have something that can recreate this (feel free to use the sample app), that would help us in making sure the solution works.

**Comment by isolino** [comment]
I am not putting NULLs inside JSONArrays.
I just put a list of custom objects inside the `com.segment.analytics.Properties` and have no problems with that.

After upgrade  the **appboy-segment-integration** from 10.0.0 to 15.0.1 the crashs starts happen.

The segment rely on `JSONObject.wrap()`  and that method returns null if the object is not a primitive/native type or a collection.

Debugging at segment dashboard. I notice that these properties, with a list of custom objects, are been ignored by Segment. The same not occurring with AppboyIntegration 15.0.1. That will crash, even with the same payload not crashing the Segment SDK.

### Workaround

I am cleaning all TrackPayloads at BrazeMiddleware. Just replacing the properties that are a  list of custom classes by nothing. And could stop the crashes.

**Comment by isolino** [comment]
I'm closing the issue,
And will apply the TrackPayload cleaning for now.
After, I will refactor all properties that are a list of custom classes.

For example.

```
Properties().apply {
   //put("customClassList", listOf(MyClass(), MyClass()))
}
```
